"""The glossary, and the shape every entry under `## Language` keeps."""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTEXT = REPO_ROOT / "CONTEXT.md"

# The heading the glossary lives under. Everything above it is the file's own
# title and its one-line statement of the domain.
SECTION = "## Language"

# An entry opens with its term in bold on a line of its own, and closes with
# the line naming what to call it instead.
TERM = re.compile(r"^\*\*[^*]+\*\*:$")
AVOID = re.compile(r"^_Avoid_: \S.*$")

# A sentence ends at a full stop, a question mark, or an exclamation mark
# followed by a space. The glossary writes no abbreviation that ends in a full
# stop, so nothing here splits a sentence in half.
SENTENCE = re.compile(r"(?<=[.!?])\s+")

# The directory holding the modules that state what is true of a term. An
# entry names one of them where its law lives there.
RULES = "docs/rules/"

# What a definition may run to before it has stopped defining a term and
# started legislating about it. Four is what the longest honest entry needs:
# what the term is, the distinction that keeps it apart from its neighbour,
# and the clause naming where its law is written (issue #265).
SENTENCES = 4


def _blocks() -> list[list[str]]:
    """Every blank-line-separated block under `## Language`, in file order."""

    text = CONTEXT.read_text(encoding="utf-8")
    _, marker, section = text.partition(SECTION)
    assert marker, f"{CONTEXT.name} carries no {SECTION} section."

    blocks: list[list[str]] = []
    for chunk in section.strip().split("\n\n"):
        lines = [line for line in chunk.splitlines() if line.strip()]
        if lines:
            blocks.append(lines)
    return blocks


def _entries() -> dict[str, list[str]]:
    """Map each term to the lines of its entry, the term line included."""

    entries: dict[str, list[str]] = {}
    for block in _blocks():
        if TERM.match(block[0]):
            entries[block[0].strip("*:")] = block
    return entries


def test_the_glossary_says_where_a_terms_law_is_written() -> None:
    """A reader has to be told what the entries stopped carrying.

    The glossary is regenerated by more than one Skill, so an entry is not a
    safe home for a sentence that lives nowhere else. Stripping the law out is
    only half of that: the other half is the sentence at the top of the section
    telling a reader where what is true of a term is now stated, so somebody
    who came here for a rule leaves with the module rather than with the
    impression that nobody wrote one (issue #265).
    """

    opening = _blocks()[0]

    assert not TERM.match(opening[0]), (
        f"{CONTEXT.name} opens {SECTION} with an entry. The section says what"
        f" an entry carries and where a term's law is stated instead."
    )
    assert RULES in "\n".join(opening), (
        f"{CONTEXT.name}'s opening under {SECTION} does not name `{RULES}`,"
        f" so a reader is left to guess where a term's law is written."
    )


def test_every_entry_is_a_term_a_definition_and_an_avoid_line() -> None:
    """An entry is three lines, and a fourth is a rule that wandered in.

    `/grill-with-docs` and `/domain-modeling` both write this file, so an entry
    is regenerable content: a sentence that lives only here is a sentence one
    regeneration destroys. Three lines is the shape that survives it — the
    bolded term, what it means, and what to call it instead — and anything
    further is law with no home of its own (issue #265).
    """

    entries = _entries()

    # A parser that matched nothing would leave the loop empty and pass.
    assert entries

    malformed = {term: len(lines) for term, lines in entries.items() if len(lines) != 3}
    assert malformed == {}, (
        f"{malformed}: an entry under {SECTION} is exactly three lines — the"
        f" bolded term, one definition, and its `_Avoid_` line."
    )

    unavoided = sorted(
        term for term, lines in entries.items() if not AVOID.match(lines[-1])
    )
    assert unavoided == [], (
        f"{unavoided}: an entry closes with `_Avoid_: ` and the names this"
        f" collection does not use for the term."
    )


def test_no_entry_states_the_law_a_rules_module_holds() -> None:
    """The entry names the module; it does not restate what the module says.

    Both failures below are the same failure: a definition long enough to be
    carrying a rule, and an entry arguing a rule it has already pointed at. The
    bound is what makes the first mechanically visible — the entries this
    ticket rewrote ran to a paragraph of law each, and the module they now
    point at is where a reader meets that law once (issue #265).
    """

    entries = _entries()
    assert entries

    overlong = {
        term: len(SENTENCE.split(lines[1]))
        for term, lines in entries.items()
        if len(SENTENCE.split(lines[1])) > SENTENCES
    }
    assert overlong == {}, (
        f"{overlong}: a definition runs to more than {SENTENCES} sentences,"
        f" which is a term explained and then legislated about. State the rule"
        f" in the module under `{RULES}` that holds it and name that module"
        f" here in one clause."
    )

    restated = {
        term: sum(RULES in sentence for sentence in SENTENCE.split(lines[1]))
        for term, lines in entries.items()
        if sum(RULES in sentence for sentence in SENTENCE.split(lines[1])) > 1
    }
    assert restated == {}, (
        f"{restated}: an entry names the module holding its law in one clause."
        f" More than one is the entry taking the module's job back."
    )
